/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const EquipmentType = IDL.Variant({
  'Car' : IDL.Null,
  'JCB' : IDL.Null,
  'Bulldozer' : IDL.Null,
  'Bike' : IDL.Null,
  'Tractor' : IDL.Null,
  'Scooty' : IDL.Null,
  'Truck' : IDL.Null,
  'Aeroplane' : IDL.Null,
  'Crane' : IDL.Null,
});
export const OrderId = IDL.Nat;
export const OrderStatus = IDL.Variant({
  'Delivered' : IDL.Null,
  'Confirmed' : IDL.Null,
  'Cancelled' : IDL.Null,
  'Shipped' : IDL.Null,
  'Pending' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const ShippingInfo = IDL.Record({
  'city' : IDL.Text,
  'name' : IDL.Text,
  'state' : IDL.Text,
  'addressLine1' : IDL.Text,
  'addressLine2' : IDL.Text,
  'phone' : IDL.Text,
  'pincode' : IDL.Text,
});
export const PartId = IDL.Nat;
export const CartItem = IDL.Record({ 'quantity' : IDL.Nat, 'partId' : PartId });
export const Order = IDL.Record({
  'id' : OrderId,
  'status' : OrderStatus,
  'total' : IDL.Nat,
  'createdAt' : Timestamp,
  'shippingInfo' : ShippingInfo,
  'items' : IDL.Vec(CartItem),
});
export const StockStatus = IDL.Variant({
  'OutOfStock' : IDL.Null,
  'LowStock' : IDL.Null,
  'InStock' : IDL.Null,
});
export const Part = IDL.Record({
  'id' : PartId,
  'specifications' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  'partNumber' : IDL.Text,
  'stockStatus' : StockStatus,
  'name' : IDL.Text,
  'equipmentType' : EquipmentType,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Nat,
  'modelCompatibility' : IDL.Vec(IDL.Text),
  'images' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  'getEquipmentModels' : IDL.Func(
      [EquipmentType],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
  'getPart' : IDL.Func([PartId], [IDL.Opt(Part)], ['query']),
  'getPartCategories' : IDL.Func(
      [EquipmentType, IDL.Opt(IDL.Text)],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getParts' : IDL.Func(
      [
        IDL.Opt(EquipmentType),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [IDL.Vec(Part)],
      ['query'],
    ),
  'placeOrder' : IDL.Func(
      [IDL.Vec(CartItem), ShippingInfo],
      [IDL.Variant({ 'ok' : OrderId, 'err' : IDL.Text })],
      [],
    ),
  'searchParts' : IDL.Func([IDL.Text], [IDL.Vec(Part)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const EquipmentType = IDL.Variant({
    'Car' : IDL.Null,
    'JCB' : IDL.Null,
    'Bulldozer' : IDL.Null,
    'Bike' : IDL.Null,
    'Tractor' : IDL.Null,
    'Scooty' : IDL.Null,
    'Truck' : IDL.Null,
    'Aeroplane' : IDL.Null,
    'Crane' : IDL.Null,
  });
  const OrderId = IDL.Nat;
  const OrderStatus = IDL.Variant({
    'Delivered' : IDL.Null,
    'Confirmed' : IDL.Null,
    'Cancelled' : IDL.Null,
    'Shipped' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const ShippingInfo = IDL.Record({
    'city' : IDL.Text,
    'name' : IDL.Text,
    'state' : IDL.Text,
    'addressLine1' : IDL.Text,
    'addressLine2' : IDL.Text,
    'phone' : IDL.Text,
    'pincode' : IDL.Text,
  });
  const PartId = IDL.Nat;
  const CartItem = IDL.Record({ 'quantity' : IDL.Nat, 'partId' : PartId });
  const Order = IDL.Record({
    'id' : OrderId,
    'status' : OrderStatus,
    'total' : IDL.Nat,
    'createdAt' : Timestamp,
    'shippingInfo' : ShippingInfo,
    'items' : IDL.Vec(CartItem),
  });
  const StockStatus = IDL.Variant({
    'OutOfStock' : IDL.Null,
    'LowStock' : IDL.Null,
    'InStock' : IDL.Null,
  });
  const Part = IDL.Record({
    'id' : PartId,
    'specifications' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
    'partNumber' : IDL.Text,
    'stockStatus' : StockStatus,
    'name' : IDL.Text,
    'equipmentType' : EquipmentType,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Nat,
    'modelCompatibility' : IDL.Vec(IDL.Text),
    'images' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    'getEquipmentModels' : IDL.Func(
        [EquipmentType],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
    'getPart' : IDL.Func([PartId], [IDL.Opt(Part)], ['query']),
    'getPartCategories' : IDL.Func(
        [EquipmentType, IDL.Opt(IDL.Text)],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getParts' : IDL.Func(
        [
          IDL.Opt(EquipmentType),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [IDL.Vec(Part)],
        ['query'],
      ),
    'placeOrder' : IDL.Func(
        [IDL.Vec(CartItem), ShippingInfo],
        [IDL.Variant({ 'ok' : OrderId, 'err' : IDL.Text })],
        [],
      ),
    'searchParts' : IDL.Func([IDL.Text], [IDL.Vec(Part)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };