/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CartItem { 'quantity' : bigint, 'partId' : PartId }
export type EquipmentType = { 'Car' : null } |
  { 'JCB' : null } |
  { 'Bulldozer' : null } |
  { 'Bike' : null } |
  { 'Tractor' : null } |
  { 'Scooty' : null } |
  { 'Truck' : null } |
  { 'Aeroplane' : null } |
  { 'Crane' : null };
export interface Order {
  'id' : OrderId,
  'status' : OrderStatus,
  'total' : bigint,
  'createdAt' : Timestamp,
  'shippingInfo' : ShippingInfo,
  'items' : Array<CartItem>,
}
export type OrderId = bigint;
export type OrderStatus = { 'Delivered' : null } |
  { 'Confirmed' : null } |
  { 'Cancelled' : null } |
  { 'Shipped' : null } |
  { 'Pending' : null };
export interface Part {
  'id' : PartId,
  'specifications' : Array<[string, string]>,
  'partNumber' : string,
  'stockStatus' : StockStatus,
  'name' : string,
  'equipmentType' : EquipmentType,
  'description' : string,
  'category' : string,
  'price' : bigint,
  'modelCompatibility' : Array<string>,
  'images' : Array<string>,
}
export type PartId = bigint;
export interface ShippingInfo {
  'city' : string,
  'name' : string,
  'state' : string,
  'addressLine1' : string,
  'addressLine2' : string,
  'phone' : string,
  'pincode' : string,
}
export type StockStatus = { 'OutOfStock' : null } |
  { 'LowStock' : null } |
  { 'InStock' : null };
export type Timestamp = bigint;
export interface _SERVICE {
  'getEquipmentModels' : ActorMethod<[EquipmentType], Array<string>>,
  'getOrder' : ActorMethod<[OrderId], [] | [Order]>,
  'getPart' : ActorMethod<[PartId], [] | [Part]>,
  'getPartCategories' : ActorMethod<
    [EquipmentType, [] | [string]],
    Array<string>
  >,
  'getParts' : ActorMethod<
    [[] | [EquipmentType], [] | [string], [] | [string], [] | [string]],
    Array<Part>
  >,
  'placeOrder' : ActorMethod<
    [Array<CartItem>, ShippingInfo],
    { 'ok' : OrderId } |
      { 'err' : string }
  >,
  'searchParts' : ActorMethod<[string], Array<Part>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];