/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Part {
    id: PartId;
    specifications: Array<[string, string]>;
    partNumber: string;
    stockStatus: StockStatus;
    name: string;
    equipmentType: EquipmentType;
    description: string;
    category: string;
    price: bigint;
    modelCompatibility: Array<string>;
    images: Array<string>;
}
export interface ShippingInfo {
    city: string;
    name: string;
    state: string;
    addressLine1: string;
    addressLine2: string;
    phone: string;
    pincode: string;
}
export type Timestamp = bigint;
export type PartId = bigint;
export interface CartItem {
    quantity: bigint;
    partId: PartId;
}
export interface Order {
    id: OrderId;
    status: OrderStatus;
    total: bigint;
    createdAt: Timestamp;
    shippingInfo: ShippingInfo;
    items: Array<CartItem>;
}
export type OrderId = bigint;
export enum EquipmentType {
    Car = "Car",
    JCB = "JCB",
    Bulldozer = "Bulldozer",
    Bike = "Bike",
    Tractor = "Tractor",
    Scooty = "Scooty",
    Truck = "Truck",
    Aeroplane = "Aeroplane",
    Crane = "Crane"
}
export enum OrderStatus {
    Delivered = "Delivered",
    Confirmed = "Confirmed",
    Cancelled = "Cancelled",
    Shipped = "Shipped",
    Pending = "Pending"
}
export enum StockStatus {
    OutOfStock = "OutOfStock",
    LowStock = "LowStock",
    InStock = "InStock"
}
export interface backendInterface {
    getEquipmentModels(equipmentType: EquipmentType): Promise<Array<string>>;
    getOrder(id: OrderId): Promise<Order | null>;
    getPart(id: PartId): Promise<Part | null>;
    getPartCategories(equipmentType: EquipmentType, model: string | null): Promise<Array<string>>;
    getParts(equipmentType: EquipmentType | null, model: string | null, category: string | null, searchQuery: string | null): Promise<Array<Part>>;
    placeOrder(items: Array<CartItem>, shippingInfo: ShippingInfo): Promise<{
        __kind__: "ok";
        ok: OrderId;
    } | {
        __kind__: "err";
        err: string;
    }>;
    searchParts(searchQuery: string): Promise<Array<Part>>;
}
import type { CartItem as _CartItem, EquipmentType as _EquipmentType, Order as _Order, OrderId as _OrderId, OrderStatus as _OrderStatus, Part as _Part, PartId as _PartId, ShippingInfo as _ShippingInfo, StockStatus as _StockStatus, Timestamp as _Timestamp } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getEquipmentModels(arg0: EquipmentType): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEquipmentModels(to_candid_EquipmentType_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEquipmentModels(to_candid_EquipmentType_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getOrder(arg0: OrderId): Promise<Order | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrder(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrder(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPart(arg0: PartId): Promise<Part | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPart(arg0);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPart(arg0);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPartCategories(arg0: EquipmentType, arg1: string | null): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPartCategories(to_candid_EquipmentType_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n15(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPartCategories(to_candid_EquipmentType_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n15(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getParts(arg0: EquipmentType | null, arg1: string | null, arg2: string | null, arg3: string | null): Promise<Array<Part>> {
        if (this.processError) {
            try {
                const result = await this.actor.getParts(to_candid_opt_n16(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n15(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n15(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n15(this._uploadFile, this._downloadFile, arg3));
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getParts(to_candid_opt_n16(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n15(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n15(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n15(this._uploadFile, this._downloadFile, arg3));
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async placeOrder(arg0: Array<CartItem>, arg1: ShippingInfo): Promise<{
        __kind__: "ok";
        ok: OrderId;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.placeOrder(arg0, arg1);
                return from_candid_variant_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeOrder(arg0, arg1);
            return from_candid_variant_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchParts(arg0: string): Promise<Array<Part>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchParts(arg0);
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchParts(arg0);
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_EquipmentType_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EquipmentType): EquipmentType {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_OrderStatus_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Part_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Part): Part {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_StockStatus_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StockStatus): StockStatus {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Order]): Order | null {
    return value.length === 0 ? null : from_candid_Order_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Part]): Part | null {
    return value.length === 0 ? null : from_candid_Part_n9(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _PartId;
    specifications: Array<[string, string]>;
    partNumber: string;
    stockStatus: _StockStatus;
    name: string;
    equipmentType: _EquipmentType;
    description: string;
    category: string;
    price: bigint;
    modelCompatibility: Array<string>;
    images: Array<string>;
}): {
    id: PartId;
    specifications: Array<[string, string]>;
    partNumber: string;
    stockStatus: StockStatus;
    name: string;
    equipmentType: EquipmentType;
    description: string;
    category: string;
    price: bigint;
    modelCompatibility: Array<string>;
    images: Array<string>;
} {
    return {
        id: value.id,
        specifications: value.specifications,
        partNumber: value.partNumber,
        stockStatus: from_candid_StockStatus_n11(_uploadFile, _downloadFile, value.stockStatus),
        name: value.name,
        equipmentType: from_candid_EquipmentType_n13(_uploadFile, _downloadFile, value.equipmentType),
        description: value.description,
        category: value.category,
        price: value.price,
        modelCompatibility: value.modelCompatibility,
        images: value.images
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _OrderId;
    status: _OrderStatus;
    total: bigint;
    createdAt: _Timestamp;
    shippingInfo: _ShippingInfo;
    items: Array<_CartItem>;
}): {
    id: OrderId;
    status: OrderStatus;
    total: bigint;
    createdAt: Timestamp;
    shippingInfo: ShippingInfo;
    items: Array<CartItem>;
} {
    return {
        id: value.id,
        status: from_candid_OrderStatus_n6(_uploadFile, _downloadFile, value.status),
        total: value.total,
        createdAt: value.createdAt,
        shippingInfo: value.shippingInfo,
        items: value.items
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    OutOfStock: null;
} | {
    LowStock: null;
} | {
    InStock: null;
}): StockStatus {
    return "OutOfStock" in value ? StockStatus.OutOfStock : "LowStock" in value ? StockStatus.LowStock : "InStock" in value ? StockStatus.InStock : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Car: null;
} | {
    JCB: null;
} | {
    Bulldozer: null;
} | {
    Bike: null;
} | {
    Tractor: null;
} | {
    Scooty: null;
} | {
    Truck: null;
} | {
    Aeroplane: null;
} | {
    Crane: null;
}): EquipmentType {
    return "Car" in value ? EquipmentType.Car : "JCB" in value ? EquipmentType.JCB : "Bulldozer" in value ? EquipmentType.Bulldozer : "Bike" in value ? EquipmentType.Bike : "Tractor" in value ? EquipmentType.Tractor : "Scooty" in value ? EquipmentType.Scooty : "Truck" in value ? EquipmentType.Truck : "Aeroplane" in value ? EquipmentType.Aeroplane : "Crane" in value ? EquipmentType.Crane : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _OrderId;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: OrderId;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Delivered: null;
} | {
    Confirmed: null;
} | {
    Cancelled: null;
} | {
    Shipped: null;
} | {
    Pending: null;
}): OrderStatus {
    return "Delivered" in value ? OrderStatus.Delivered : "Confirmed" in value ? OrderStatus.Confirmed : "Cancelled" in value ? OrderStatus.Cancelled : "Shipped" in value ? OrderStatus.Shipped : "Pending" in value ? OrderStatus.Pending : value;
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Part>): Array<Part> {
    return value.map((x)=>from_candid_Part_n9(_uploadFile, _downloadFile, x));
}
function to_candid_EquipmentType_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EquipmentType): _EquipmentType {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EquipmentType | null): [] | [_EquipmentType] {
    return value === null ? candid_none() : candid_some(to_candid_EquipmentType_n1(_uploadFile, _downloadFile, value));
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EquipmentType): {
    Car: null;
} | {
    JCB: null;
} | {
    Bulldozer: null;
} | {
    Bike: null;
} | {
    Tractor: null;
} | {
    Scooty: null;
} | {
    Truck: null;
} | {
    Aeroplane: null;
} | {
    Crane: null;
} {
    return value == EquipmentType.Car ? {
        Car: null
    } : value == EquipmentType.JCB ? {
        JCB: null
    } : value == EquipmentType.Bulldozer ? {
        Bulldozer: null
    } : value == EquipmentType.Bike ? {
        Bike: null
    } : value == EquipmentType.Tractor ? {
        Tractor: null
    } : value == EquipmentType.Scooty ? {
        Scooty: null
    } : value == EquipmentType.Truck ? {
        Truck: null
    } : value == EquipmentType.Aeroplane ? {
        Aeroplane: null
    } : value == EquipmentType.Crane ? {
        Crane: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
